print("Potenciacion")
print(2 ** 3)
print(2 ** 3.)
print(2. ** 3)
print(2. ** 3.)
print()
print("Multiplicacion")
print(2 * 3)
print(2 * 3.)
print(2. * 3)
print(2. * 3.)
print()
print("Division")
print(6 / 3)
print(6 / 3.)
print(6. / 3)
print(6. / 3.)
print(6 // 3)
print(6 // 3.)
print(6. // 3)
print(6. // 3.)
print(6 // 4) #El resultado de la división entera siempre se redondea al valor entero inferior mas cercano del resultado de la división no redondeada
print(6. // 4)
print(-6 // 4)
print(6. // -4)
print()
print("Modulo o Residuo")
print(14 % 4)
print(12 % 4.5)
print()
print("Suma")
print(-4 + 4)
print(-4. + 8)
print()
print("Resta")
print(-4 - 4)
print(4. - 8)
print(--1.1)

