print("La Witsi Witsi Araña\nsubió a su telaraña.\n")
print("Vino la lluvia\ny se la llevó.\n")
print("La Witsi Witsi Araña" , "subió" , "a su telaraña.\n")
print("Mi nombre es", "Python." ,end=" ")
print("Monty Python.")
print()
print("Mi", "nombre", "es", "Monty", "Python.", sep="-")
print()
print("Mi", "nombre", "es", sep="_", end="*")
print("Monty", "Python.", sep="*", end="*\n")
print()
print("Fundamentos","Programación","en",sep="***",end="...")
print("Python")
print()
print("Krlos "*2)
print()
print('Me gusta "Monty Python"')
print("Me gusta \"Monty Python\"")
print()
print('"Estoy"\n""aprendiendo""\n"""Python"""')
print()
var = "3.8.5"
print("Versión de Python: " + var)

x=input()
y=input()
print(x+y)
